# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ffca5e20c6e66e3532bd5f1933d78f7c53646f34d940e062fb684613457b192b5ae31fee58d800e186a64460f7e7cc114fa803493f4123347c4f4642e29e51d7

test:
  secret_key_base: e7cb22cb1ede68df539eb09bca76cd8a08e6bae4dcb4c718530d6c120b797cbd85da6b936d14387769b85edade09ea4bf8bd18f6ea66cc402dc75fd5a090568e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
